# class InvalidTopicName(Exception):
#     ...

# class InvalidGroupId(Exception):
#     ...

class SendingError(Exception):
    ...

class UnkownArgumentError(ValueError):
    ...

class ActionError(Exception):
    ...

class TrasnactionPreparingError(ActionError):
    ...


class UmountAction:
    ...